# Odometry model
odom_model_type : diff
odom_alpha1     : 7
odom_alpha2     : 7
odom_alpha3     : 7
odom_alpha4     : 7
odom_alpha5     : 7

# Particle filter
min_particles     : 100
max_particles     : 5000
kld_err           : 0.01
kld_z             : 0.99
update_min_d      : 0.1
update_min_a      : 0.1
resample_interval : 1

# Measurement (laser) model
laser_model_type   : likelihood_field
laser_max_beams    : 60
laser_max_range    : 12.0
laser_z_hit        : 0.95
laser_z_short      : 0.1
laser_z_max        : 0.05
laser_z_rand       : 0.05
laser_sigma_hit    : 0.2
laser_lambda_short : 0.1
laser_likelihood_max_dist : 2.0

# Update/Rate params
transform_tolerance : 0.1
gui_publish_rate    : 10.0

# Recovery:
recovery_alpha_slow : 0.0
recovery_alpha_fast : 0.0

# Frames:
odom_frame_id : odom
