map_frame : map
base_frame: base_footprint
odom_frame: odom

map_update_interval: 1.0

maxUrange: 9.0
maxRange : 10.0

linearUpdate     :  0.1
angularUpdate    :  0.2

xmin : -50.0
ymin : -50.0
xmax :  50.0
ymax :  50.0
delta:  0.05
