map_frame : map
base_frame: base_footprint
odom_frame: odom

use_tf_scan_transformation: true
use_tf_pose_start_estimate: false
pub_map_odom_transform    : true

map_resolution       : 0.075
map_size             : 2048
map_start_x          : 0.5
map_start_y          : 0.5
map_multi_res_levels : 2

update_factor_free         : 0.4
update_factor_occupied     : 0.9    
map_update_distance_thresh : 0.2
map_update_angle_thresh    : 0.4
laser_z_min_value          : -2.5
laser_z_max_value          : 3.5
laser_max_dist             : 5.0
    
advertise_map_service : true
    
scan_subscriber_queue_size : 25

tf_map_scanmatch_transform_frame_name : scanmatcher_frame