map_frame : map
base_frame: base_footprint
odom_frame: odom

map_pub_period: 1.0

map_resolution       : 0.05
map_size             : 2048
   
map_update_distance_thresh : 0.1
map_update_angle_thresh    : 0.2
laser_max_dist             : 5.0
 

tf_map_scanmatch_transform_frame_name : scanmatcher_frame