local_costmap:
    map_type: costmap
    
    global_frame: odom
    robot_base_frame: base_footprint
    transform_tolerance: 10.0
    
    update_frequency: 4.0
    publish_frequency: 3.0
    
    static_map: false
    rolling_window: true
    width: 5.0
    height: 5.0
    
    resolution: 0.05 
    static_map: false

    robot_radius: 0.30  
    
    rolling_window: true

    plugins:
        - {name: obstacles_laser_layer,     type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}
        - {name: footprint_layer,           type: "costmap_2d::FootprintLayer"}
    
    obstacles_laser_layer:
        enabled: true
        observation_sources: laser
        laser: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, expected_update_rate: 0.3, observation_persistence: 1.0, inf_is_valid: true, marking: true, clearing: true, raytrace_range: 3.0, obstacle_range: 2.5, min_obstacle_height: -0.1, max_obstacle_height: 0.2, topic_name: scan}
        combination_method: 1 

    inflation_layer:
        enabled: true
        inflation_radius: 0.3
        cost_scaling_factor: 3.0
        
    footprint_layer:
        enabled: true
