global_costmap:
    
    map_type: costmap 
    
    global_frame: map
    robot_base_frame: base_footprint
    
    update_frequency: 4.0
    publish_frequency: 3.0
    transform_tolerance: 10.0
    
    resolution: 0.05  

    track_unknown_space: true  
    unknown_cost_value: 255

    robot_radius: 0.30
    
    rolling_window: false
    static_map: true
    

    plugins:
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: obstacles_laser_layer,   type: "costmap_2d::ObstacleLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: footprint_layer,         type: "costmap_2d::FootprintLayer"}
        
    static_layer:
        enabled: true
        subscribe_to_updates: true
        map_topic: /map
  
    obstacles_laser_layer:
        enabled: true
        observation_sources: laser
        laser: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, expected_update_rate: 0.3, observation_persistence: 1.0, inf_is_valid: true, marking: true, clearing: true, raytrace_range: 3.0, obstacle_range: 2.5, min_obstacle_height: -0.1, max_obstacle_height: 0.2, topic_name: scan}
        combination_method: 0
        
    inflation_layer:
        enabled: true
        inflation_radius: 0.3
        cost_scaling_factor: 3.0
        
    footprint_layer:
        enabled: true