controller_frequency: 5.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: false 
  default_tolerance: 0.5
  visualize_potential: true
  
GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.5
  visualize_potential: true
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  last_plan_if_blocked: true
  neutral_cost: 80
  cost_factor: 0.5

TrajectoryPlannerROS:

  acc_lim_th: !degrees 60.0
  acc_lim_theta: !degrees 60.0
  acc_lim_x: 0.8
  acc_lim_y: 0.0

  max_vel_x: 1.00
  min_vel_x: 0.01
  max_vel_theta: !degrees 60.0
  min_vel_theta: !degrees -60.0
  min_in_place_vel_theta: !degrees 20.0
  max_rotational_vel: !degrees 60.0
  min_in_place_rotational_vel: !degrees 20.0  

  escape_vel: 0.0

  yaw_goal_tolerance: !degrees 10.0
  xy_goal_tolerance: 0.2

  sim_time: 1.0
  vx_samples: 10
  vtheta_samples: 20

  meter_scoring: true 
  occdist_scale:  0.01 
  pdist_scale: 1.2  
  gdist_scale: 0.8
  heading_scale: 0.3
  
  path_distance_bias: 1.2
  goal_distance_bias: 0.8

  heading_lookahead: 0.325  
  heading_scoring: false  
  heading_scoring_timestep: 0.1   
  dwa: true 

  oscillation_reset_dist: 0.05

  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  vy_samples: 0
  
  prune_plan: true
  
  publish_cost_grid: true

DWAPlannerROS:

  acc_lim_x: 0.8
  acc_lim_y: 0.0
  acc_lim_th: 1.5

  max_vel_x: 1.5
  min_vel_x: 0.0
  
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_vel_trans: 1.5
  min_vel_trans: 0.1
  
  max_vel_theta: 2.0
  min_vel_theta: 0.4
  
  sim_time: 1.7
  sim_granularity: 0.025

  goal_distance_bias: 24.0
  path_distance_bias: 32.0
  occdist_scale: 0.01
  
  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.1
  
  forward_point_distance: 0.325
  
  scaling_speed: 1.0
  max_scaling_factor: 0.2
  
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20
  
  sim_period: 0.1
  
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  
  rot_stopped_vel: 0.01
  trans_stopped_vel: 0.01
  
  meter_scoring: true
  publish_cost_grid: true
  
TebLocalPlannerROS:

  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  global_plan_overwrite_orientation: true
  max_global_plan_lookahead_dist: 5.0
  feasibility_check_no_poses: 5
  global_plan_viapoint_sep: 1.0
  min_samples: 5
  exact_arc_length: true
  allow_init_with_backwards_motion: false
  
  max_vel_x: 0.5
  max_vel_x_backwards: 0.15
  max_vel_theta: 0.6
  acc_lim_x: 0.2
  acc_lim_theta: !degrees 45.0
  is_footprint_dynamic: false
  footprint_model:
    type: "circular"
    radius: 0.27

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  free_goal_vel: False

  min_obstacle_dist: 0.06
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  inflation_dist: 0.5

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 10
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 500
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 1
  weight_obstacle: 50
  weight_inflation: 5.0
  weight_dynamic_obstacle: 10 
  selection_alternative_time_cost: false
  weight_viapoint: 0.75

  enable_homotopy_class_planning: false
  enable_multithreading: true
  simple_exploration: false
  max_number_classes: 4
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_keypoint_offset: 0.1
  obstacle_heading_threshold: 0.45
  visualize_hc_graph: false
