planner_frequency: 2.0
planner_patience: 0.1

controller_frequency: 10.0
controller_patience: 3.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behaviour_enabled: true
shutdown_costmaps: false

search_alternative_goals: true
alternative_goals_thresh: 0.5
latch_xy_goal_tolerance: true


NavfnROS:
  allow_unknown: false 
  default_tolerance: 0.5
  visualize_potential: true
  
GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.5
  visualize_potential: true
  
  use_dijkstra: true
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  last_plan_if_blocked: true
  neutral_cost: 80
  cost_factor: 0.5

DWAPlannerROS:

  acc_lim_x: 0.8
  acc_lim_y: 0.0
  acc_lim_th: 1.5
  
  max_vel_x: 0.9
  min_vel_x: 0.1
  
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_trans_vel: 0.5
  min_trans_vel: 0.1
  
  max_rot_vel: 1.0
  min_rot_vel: 0.2
  
  sim_time: 4.0
  
  vx_samples: 10
  vy_samples: 0
  vtheta_samples: 20
  
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance : 0.2
  latch_xy_goal_tolerance: false
  
  


