controller_frequency: 5.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: false 
  default_tolerance: 0.5
  visualize_potential: true
  
GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.5
  visualize_potential: true
  use_dijkstra: false
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  last_plan_if_blocked: true
  neutral_cost: 80
  cost_factor: 0.5

DWAPlannerROS:

  acc_lim_x: 0.8
  acc_lim_y: 0.0
  acc_lim_th: 1.5
  
  max_vel_trans: 1.0
  min_vel_trans: 0.1

  max_vel_x: 1.0
  min_vel_x: 0.0
  
  max_vel_y: 0.0
  min_vel_y: 0.0

  max_rot_vel: 2.0
  min_rot_vel: 0.4
  
  sim_time: 3
  sim_granularity: 0.025

  scaling_speed: 1.0
  
  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40
  
  meter_scoring: true
  publish_cost_grid: true
  
TebLocalPlannerROS:

  max_vel_x: 1.0
  max_vel_x_backwards: 0.1
  max_vel_theta: 2.0
  
  acc_lim_x: 0.8
  acc_lim_theta: 1.5
  
  min_samples: 5

  footprint_model:
    type: "circular"
    radius: 0.27

  exact_arc_length: true
  
  enable_homotopy_class_planning: false
