recovery_behaviors:

  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'super_conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'conservative_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'aggressive_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

super_conservative_reset:
  reset_distance: 5.5
  layer_names: ["obstacle_laser_layer"]

conservative_reset:
  reset_distance: 3.0
  layer_names: ["obstacle_laser_layer"]
  
aggressive_reset:
  reset_distance: 1.5
  layer_names: ["obstacle_laser_layer"]    