recovery_behaviors:

  - name: 'rotate_recovery'
    type: 'rotate_recovery/RotateRecovery'
  - name: 'super_far_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'far_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'close_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

super_far_reset:
  reset_distance: 5.5
  layer_names: ["obstacle_laser_layer"]

far_reset:
  reset_distance: 3.0
  layer_names: ["obstacle_laser_layer"]
  
close_reset:
  reset_distance: 1.5
  layer_names: ["obstacle_laser_layer"]    